version: '3'

services:

  app:
    image: snipe/snipe-it
    restart: unless-stopped
    env_file: my_env_file
    ports:
      - 8080:80
    depends_on:
      - db
      - mail
    volumes:
      - ./snipeit:/var/lib/snipeit

  db:
    image: mysql:5.6
    restart: unless-stopped
    env_file: my_env_file
    volumes:
      - ./data:/var/lib/mysql

  mail:
    image: catatnight/postfix
    restart: unless-stopped
    environment:
      - maildomain=example.com
      - smtp_user=postfix:postfix
