version: '3'

services:

  app:
    image: snipe/snipe-it
    restart: unless-stopped


  db:
    image: mysql:5.6
    restart: unless-stopped
    env_file: my_env_file
    volumes:
      - ./data:/var/lib/mysql
