version: '3'

services:

  app:
    image: snipe/snipe-it
    restart: unless-stopped
    env_file: .env
    ports:
      - 8080:80
    environment:
      - APP_KEY=
      - APP_URL=http://127.0.0.1:8080
      - MAIL_FROM_ADDR=you@example.com
      - MAIL_REPLYTO_ADDR=you@example.com
    depends_on:
      - db
      - mail
    volumes:
      - ./snipeit:/var/lib/snipeit

  db:
    image: mysql:5.6
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/var/lib/mysql

  mail:
    image: catatnight/postfix
    restart: unless-stopped
    environment:
      - maildomain=example.com
      - smtp_user=postfix:postfix
